#!/bin/bash

ensure_in_bash_profile() {
    LINE=$1
    FILE=$2

    touch "${FILE}"
    grep -xq "${LINE}" "${FILE}" || echo "${LINE}" >> "${FILE}"
}

SETUP_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# bash setting
echo "Linking project bash_profile into ~/.bash_profile."
ensure_in_bash_profile "source $SETUP_DIRECTORY/bash_profile" ~/.bash_profile
ensure_in_bash_profile "source $SETUP_DIRECTORY/cpt-completion.bash" ~/.bash_profile

# zsh setting
echo "Linking project bash_profile into .~/.zshrc."
ensure_in_bash_profile "source $SETUP_DIRECTORY/bash_profile" ~/.zshrc
ensure_in_bash_profile "autoload bashcompinit" ~/.zshrc
ensure_in_bash_profile "bashcompinit" ~/.zshrc
ensure_in_bash_profile "source $SETUP_DIRECTORY/cpt-completion.bash" ~/.zshrc
